### ISSUE TITLE
Key not generating on newer bukkit/spigot servers

### ISSUE THREAD

**Issue by Bob1nz** [JayWood/WooMinecraft#4]
Hi I compiled your plugin using 1.6.4 bukkit hoping for some backwards compatibility for the newer Spigot 1.8. 
It seems that the key is not generating when running /woo register and returns "null"

**Comment by stoi2m1** [comment]
@Bob1nz did you ever get this working with 1.8. I building a new server with version 1.8 and have been seeking a donation plugin. I really dont want to settle with one of the store hosting alternatives like enjin or buycraft. What did you end up using if you didnt get this working?

**Comment by JayWood** [comment]
Moving ALL tickets over to the new repository, sorry for my absence.  Please re-address all tickets over  at [WooMinecraft/WooMinecraft](https://github.com/WooMinecraft/WooMinecraft)
