### ISSUE TITLE
ConInfo

### ISSUE THREAD

**Issue by TekkitCommando** [JayWood/WooMinecraft#7]
@JayWood What was ConInfo gonna be used for, or maybe its referenced in another class and i just didn't look hard enough xD

**Comment by JayWood** [comment]
@TekkitCommando I believe I was following a tutorial related strictly to database manipulations in java.  My original idea was to directly access the WordPress database and grab the data that way, but that was before I realized that sending data to the Java in a JSON format would be better.

Short of it, ConInfo is just useless at this point.

**Comment by TekkitCommando** [comment]
@JayWood Ok Thanks :)
